# Generated by Django 4.0.3 on 2022-06-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.notes'),
        ),
    ]
