# Generated by Django 4.0.3 on 2022-06-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_rename_notes_contact_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='note',
            new_name='notes',
        ),
    ]
